name: .NET Core Builds

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        build-config: [ Debug, Release ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ matrix.build-config }} --no-restore
    - name: Test
      run: dotnet test --configuration ${{ matrix.build-config }} --no-restore --verbosity normal ./Test.AMT.Extensions.System/Test.AMT.Extensions.System.csproj
    # NOTE: does not test /Test.AMT.Extensions.Logging at GitHub b/c fails w/IP port comms.